DROP TABLE REMINDERS IF EXISTS;

DROP SEQUENCE IF EXISTS REMINDERS_SEQ;

CREATE SEQUENCE REMINDERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE REMINDERS (
	REMINDER_ID BIGINT NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	DESCRIPTION CLOB(2147483647), 
	DUE_DATE DATE(10), 
	STATUS CHAR(10) NOT NULL, 
	VERSION INTEGER NOT NULL, 
	PRIMARY KEY (REMINDER_ID)
)
